# Generated by Django 4.1.7 on 2023-12-02 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_hatching", models.DateField()),
                (
                    "chicken_type",
                    models.CharField(
                        choices=[
                            ("Broilers", "Broiler"),
                            ("Layers", "Layers"),
                            ("Multi-Purpose", "Multi Purpose"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "initial_number_of_birds",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(2)]
                    ),
                ),
                (
                    "current_rearing_method",
                    models.CharField(
                        choices=[
                            ("Free Range", "Free Range"),
                            ("Cage System", "Cage System"),
                            ("Deep Litter", "Deep Litter"),
                            ("Barn System", "Barn System"),
                            ("Pasture Based", "Pasture Based"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_established", models.DateField(auto_now_add=True)),
                ("is_present", models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="FlockBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Kuroiler", "Kuroiler"),
                            ("Rainbow Rooster", "Rainbow Rooster"),
                            ("Kenbro", "Kenbro"),
                            ("Indigenous", "Indigenous"),
                            ("Leghorn", "Leghorn"),
                            ("Sussex", "Sussex"),
                            ("Plymouth Rock", "Plymouth Rock"),
                            ("Rhode Island Red", "Rhode Island Red"),
                            ("Brahma", "Brahma"),
                            ("Cornish Cross", "Cornish Cross"),
                            ("Australorp", "Australorp"),
                            ("Orpington", "Orpington"),
                            ("Wyandotte", "Wyandotte"),
                            ("Silkie", "Silkie"),
                            ("Cochin", "Cochin"),
                            ("Easter Egger", "Easter Egger"),
                            ("Bantam", "Bantam"),
                            ("Sasso F1", "Sasso F1"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("This Farm", "This Farm"),
                            ("Ken Chick", "Ken Chick"),
                            ("Kuku Chick", "Kuku Chick"),
                            ("Uzima Chicken", "Uzima Chicken"),
                            ("Kiplel's Farm", "Kiplels Farm"),
                        ],
                        max_length=13,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HousingStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("Open-Sided Shed", "Open Sided Shed"),
                            ("Closed Shed", "Closed Shed"),
                            ("Battery Cage System", "Battery Cage"),
                            ("Deep Litter House", "Deep Litter House"),
                            ("Semi-Intensive Housing", "Semi Intensive Housing"),
                            ("Pasture Housing", "Pasture Housing"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Brooder Chick House", "Brooder Chick House"),
                            ("Growers House", "Growers House"),
                            ("Layers House", "Layers House"),
                            ("Broilers House", "Broilers House"),
                            ("Breeders House", "Breeders House"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_date", models.DateField(auto_now_add=True)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poultry.flock"
                    ),
                ),
                (
                    "from_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_movements",
                        to="poultry.housingstructure",
                    ),
                ),
                (
                    "to_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_movements",
                        to="poultry.housingstructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockInspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_inspection", models.DateTimeField(auto_now_add=True)),
                ("number_of_dead_birds", models.PositiveIntegerField(default=0)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poultry.flock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rearing_method",
                    models.CharField(
                        choices=[
                            ("Free Range", "Free Range"),
                            ("Cage System", "Cage System"),
                            ("Deep Litter", "Deep Litter"),
                            ("Barn System", "Barn System"),
                            ("Pasture Based", "Pasture Based"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
                (
                    "current_housing_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poultry.housingstructure",
                    ),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poultry.flock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockBreedInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chicken_type",
                    models.CharField(
                        choices=[
                            ("Broilers", "Broiler"),
                            ("Layers", "Layers"),
                            ("Multi-Purpose", "Multi Purpose"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "average_mature_weight_in_kgs",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("average_egg_production", models.PositiveIntegerField(null=True)),
                (
                    "maturity_age_in_weeks",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(24),
                        ]
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poultry.flockbreed",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flock",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flocks",
                to="poultry.flockbreed",
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="current_housing_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flocks",
                to="poultry.housingstructure",
            ),
        ),
        migrations.AddField(
            model_name="flock",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flocks",
                to="poultry.flocksource",
            ),
        ),
        migrations.CreateModel(
            name="EggCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_collection", models.DateField(auto_now_add=True)),
                ("time_of_collection", models.TimeField(auto_now_add=True)),
                ("collected_eggs", models.PositiveIntegerField(default=0)),
                ("broken_eggs", models.PositiveIntegerField(default=0)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poultry.flock"
                    ),
                ),
            ],
        ),
    ]
