# Generated by Django 3.2.15 on 2023-02-15 06:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Friesian', 'Friesian'), ('Ayrshire', 'Ayrshire'), ('Jersey', 'Jersey'), ('Crossbreed', 'Crossbreed'), ('Guernsey', 'Guernsey')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 15))])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('availability_status', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead'), ('S', 'Sold')], default='A', max_length=1)),
                ('pregnancy_status', models.CharField(choices=[('P', 'Pregnant'), ('C', 'Calved'), ('N', 'Not Pregnant')], default='N', max_length=1)),
                ('date_of_death', models.DateField(blank=True, error_messages={'max_value': 'The date of death cannot be in the future!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 15))])),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breed', to='dairy.breed')),
                ('calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dams', to='dairy.cow')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calves', to='dairy.cow')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offspring', to='dairy.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_time_value', models.IntegerField(choices=[(1, 'Morning'), (2, 'Mid-Morning'), (3, 'Evening'), (4, 'Night')], editable=False)),
                ('milking_date', models.DateTimeField(auto_now_add=True)),
                ('amount_in_kgs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount of milk can not be less than 0 Kgs.'), django.core.validators.MaxValueValidator(35, message='Amount of milk cannot be more than 35.0 Kgs.')], verbose_name='Amount (kg)')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='dairy.cow')),
            ],
            options={
                'verbose_name_plural': 'Milk',
                'unique_together': {('cow', 'milking_time_value')},
            },
        ),
    ]
