# Generated by Django 4.1.7 on 2023-02-20 08:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(choices=[('Friesian', 'Friesian'), ('Ayrshire', 'Ayrshire'), ('Jersey', 'Jersey'), ('Crossbreed', 'Crossbreed'), ('Guernsey', 'Guernsey')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 20))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, error_messages={'max_value': 'The date of death cannot be in the future!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 20))]),
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('date_of_calving', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed'), ('F', 'Failed')], default='U', max_length=1)),
                ('pregnancy_notes', models.TextField(blank=True)),
                ('calving_notes', models.TextField(blank=True)),
                ('pregnancy_scan_date', models.DateField(blank=True, null=True)),
                ('pregnancy_failed_date', models.DateField(blank=True, error_messages={'max_value': 'Future records not allowed!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 20))])),
                ('is_pregnant', models.BooleanField(default=True, editable=False)),
                ('pregnancy_outcome', models.CharField(blank=True, choices=[('L', 'Live'), ('S', 'Stillborn'), ('M', 'Miscarriage')], max_length=1, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='dairy.cow')),
            ],
            options={
                'verbose_name_plural': 'Pregnacy records',
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.cow')),
            ],
            options={
                'verbose_name_plural': 'Heat records',
            },
        ),
        migrations.CreateModel(
            name='Lactation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('_end_date', models.DateField(blank=True, null=True)),
                ('lactation_stage', models.IntegerField(choices=[(1, 'Early'), (2, 'Mid'), (3, 'Late'), (4, 'Dry')], editable=False)),
                ('lactation_number', models.PositiveSmallIntegerField(default=1)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy.cow')),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairy.pregnancy')),
            ],
            options={
                'verbose_name_plural': 'Lactation records',
                'unique_together': {('start_date', 'cow')},
            },
        ),
    ]
