# Generated by Django 4.1.7 on 2023-02-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_alter_breed_name_alter_cow_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lactation',
            old_name='_end_date',
            new_name='end_date',
        ),
    ]
