# Generated by Django 4.1.7 on 2023-02-24 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_alter_cow_date_of_birth_alter_cow_date_of_death_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Enter weight in Kgs.', max_digits=6, validators=[django.core.validators.MinValueValidator(1, message="Invalid weight. A cow's minimum weight record can not be less than 1 Kgs."), django.core.validators.MaxValueValidator(1500, message="Invalid weight. A cow's maximum weight can not exceed 1500 Kgs.")])),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lactation',
            options={'get_latest_by': 'start_date', 'verbose_name_plural': 'Lactation'},
        ),
        migrations.AlterUniqueTogether(
            name='milk',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lactation',
            name='lactation_stage',
        ),
        migrations.AddField(
            model_name='milk',
            name='lactation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dairy.lactation'),
        ),
        migrations.AlterField(
            model_name='lactation',
            name='cow',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='dairy.cow'),
        ),
        migrations.AlterField(
            model_name='lactation',
            name='end_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lactation',
            name='lactation_number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='lactation',
            name='pregnancy',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dairy.pregnancy'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='amount_in_kgs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Amount of milk can not be less than 0 Kgs.'), django.core.validators.MaxValueValidator(35, message='Amount of milk cannot be more than 35.0 Kgs.')], verbose_name='Amount (kg)'),
        ),
        migrations.AddConstraint(
            model_name='milk',
            constraint=models.UniqueConstraint(fields=('cow', 'milking_date'), name='unique_milk_record'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.cow'),
        ),
        migrations.RemoveField(
            model_name='milk',
            name='milking_time_value',
        ),
        migrations.AlterUniqueTogether(
            name='weightrecord',
            unique_together={('cow', 'date')},
        ),
    ]
