# Generated by Django 4.1.7 on 2023-04-11 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkinventory',
            name='total_amount_in_kgs',
            field=models.FloatField(default=0.0, editable=False, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount (kg)'),
        ),
    ]
