# Generated by Django 4.1.7 on 2023-04-11 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_in_kgs', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount (kg)')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milk Inventory',
                'verbose_name_plural': 'Milk Inventory',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='MilkInventoryUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_kgs_change', models.DecimalField(decimal_places=2, editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name=' Change in Amount (Kgs)')),
                ('update_type', models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed')], editable=False, max_length=7, verbose_name='Update Type')),
                ('amount_in_kgs', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total Amount (kg)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Milk Inventory Update History',
                'verbose_name_plural': 'Milk Inventory Update History',
                'ordering': ['-date'],
            },
        ),
    ]
