# Generated by Django 4.1.7 on 2023-04-11 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_inventory', '0002_alter_milkinventory_total_amount_in_kgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkinventory',
            name='total_amount_in_kgs',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount (kg)'),
        ),
    ]
