# Generated by Django 4.1.7 on 2023-03-09 09:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cow',
            options={'verbose_name': 'Cow 🐄', 'verbose_name_plural': 'Cows 🐄'},
        ),
        migrations.AlterModelOptions(
            name='lactation',
            options={'get_latest_by': 'start_date', 'verbose_name': 'Lactation 🍼', 'verbose_name_plural': 'Lactations 🍼'},
        ),
        migrations.AlterModelOptions(
            name='milk',
            options={'verbose_name': 'Milk 🥛', 'verbose_name_plural': 'Milk 🥛'},
        ),
        migrations.AlterModelOptions(
            name='pregnancy',
            options={'verbose_name': 'Pregnancies 🤰', 'verbose_name_plural': 'Pregnancies 🤰'},
        ),
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'verbose_name': 'Weight ⚖', 'verbose_name_plural': 'Weight ⚖'},
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='image',
        ),
        migrations.AlterField(
            model_name='cow',
            name='availability_status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Sold', 'Sold')], default='Alive', max_length=5),
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(choices=[('Friesian', 'Friesian'), ('Ayrshire', 'Ayrshire'), ('Jersey', 'Jersey'), ('Crossbreed', 'Crossbreed'), ('Guernsey', 'Guernsey')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, error_messages={'max_value': 'The date of death cannot be in the future!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='cow',
            name='pregnancy_status',
            field=models.CharField(choices=[('Pregnant', 'Pregnant'), ('Calved', 'Calved'), ('Not Pregnant', 'Not Pregnant')], default='Not Pregnant', max_length=12),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='date_of_insemination',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pregnancy_failed_date',
            field=models.DateField(blank=True, error_messages={'max_value': 'Future records not allowed!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_expiry',
            field=models.DateField(error_messages={'min_value': 'Invalid date entry, Date of expiry must be in future'}, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_production',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates of production must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='date_observed',
            field=models.DateField(error_messages={'max_value': 'The date of observation cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 3, 9))]),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
