# Generated by Django 4.1.7 on 2023-09-10 07:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lactation",
            options={"get_latest_by": "-start_date"},
        ),
        migrations.AlterModelOptions(
            name="milk",
            options={"get_latest_by": "-milking_date"},
        ),
        migrations.AlterModelOptions(
            name="semen",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="milk",
            name="unique_milk_record",
        ),
        migrations.AlterField(
            model_name="lactation",
            name="cow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lactations",
                to="dairy.cow",
            ),
        ),
        migrations.AlterField(
            model_name="lactation",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="lactation",
            name="lactation_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="lactation",
            name="pregnancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dairy.pregnancy",
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="amount_in_kgs",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=4, verbose_name="Amount (kgs)"
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="cow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_records",
                to="dairy.cow",
            ),
        ),
        migrations.AlterField(
            model_name="semen",
            name="date_of_expiry",
            field=models.DateField(
                error_messages={
                    "min_value": "Invalid date entry, Date of expiry must be in future"
                },
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 9, 10))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="semen",
            name="date_of_production",
            field=models.DateField(
                error_messages={
                    "max_value": "Invalid date entry, Dates of production must not be in future"
                },
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 9, 10))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="semen",
            name="producer",
            field=models.CharField(
                choices=[
                    ("Kenya Agricultural and Livestock Research Organization", "Kalro"),
                    ("Kenya Agricultural and Livestock Research Institute", "Kagric"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="symptoms",
            name="date_observed",
            field=models.DateField(
                error_messages={
                    "max_value": "The date of observation cannot be in the future!."
                },
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 9, 10))
                ],
            ),
        ),
    ]
