# Generated by Django 4.1.7 on 2023-10-23 04:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quarantinerecord",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Sick Cow", "Sick Cow"),
                    ("Bought Cow", "Bought Cow"),
                    ("New Cow", "New Cow"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="semen",
            name="date_of_expiry",
            field=models.DateField(
                error_messages={
                    "min_value": "Invalid date entry, Date of expiry must be in future"
                },
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2023, 10, 23)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="semen",
            name="date_of_production",
            field=models.DateField(
                error_messages={
                    "max_value": "Invalid date entry, Dates of production must not be in future"
                },
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2023, 10, 23)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="symptoms",
            name="date_observed",
            field=models.DateField(
                error_messages={
                    "max_value": "The date of observation cannot be in the future!."
                },
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2023, 10, 23)
                    )
                ],
            ),
        ),
    ]
