# Generated by Django 4.2.2 on 2023-07-31 05:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_cowbreed_alter_cow_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cow',
            options={},
        ),
        migrations.RemoveField(
            model_name='cow',
            name='calf',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='pregnancy_status',
        ),
        migrations.AddField(
            model_name='cow',
            name='category',
            field=models.CharField(choices=[('Calf', 'Calf'), ('Weaner', 'Weaner'), ('Heifer', 'Heifer'), ('Bull', 'Bull'), ('Milking Cow', 'Milking Cow')], default='Calf', max_length=11),
        ),
        migrations.AddField(
            model_name='cow',
            name='current_pregnancy_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pregnant', 'Pregnant'), ('Calved', 'Calved'), ('Unavailable', 'Unavailable')], default='Unavailable', max_length=12),
        ),
        migrations.AddField(
            model_name='cow',
            name='current_production_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pregnant not Lactating', 'Pregnant Not Lactating'), ('Pregnant and Lactating', 'Pregnant And Lactating'), ('Dry', 'Dry'), ('Culled', 'Culled'), ('Bull', 'Bull'), ('Young Bull', 'Young Bull'), ('Young Heifer', 'Young Heifer'), ('Mature Bull', 'Mature Bull'), ('Calf', 'Calf'), ('Weaner', 'Weaner')], default='Calf', max_length=22),
        ),
        migrations.AddField(
            model_name='cow',
            name='date_introduced_in_farm',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cow',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='dairy.cowbreed'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='dairy.cow'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='cow',
            name='sire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='dairy.cow'),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='date_of_insemination',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 31))]),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pregnancy_failed_date',
            field=models.DateField(blank=True, error_messages={'max_value': 'Future records not allowed!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 31))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_expiry',
            field=models.DateField(error_messages={'min_value': 'Invalid date entry, Date of expiry must be in future'}, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 31))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_production',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates of production must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 31))]),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='date_observed',
            field=models.DateField(error_messages={'max_value': 'The date of observation cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 31))]),
        ),
    ]
